import fs from 'fs';
import path from 'path';
import type {ColorTheme} from '..';
import {opacity, specificity} from './utils';

const ansiColors = {
  white: '#dbdae8',
  gray: '#90a5c8',
  black: '#0c0e15',
  red: '#ff4762',
  orange: '#dd9046',
  yellow: '#efbd5d',
  green: '#8acd5b',
  blue: '#41a7fc', // #61afef
  cyan: '#3dacb4',
  indigo: '',
  violet: '#c77ddd',
  magenta: '#d44dae',
};

const pastelColors = {
  pastelBlue: '#92d6cf',
  pastelGreen: '#add692',
  pastelGray: '#455573',
};

const vibrantColors = {
  vibrantOrange: '#ff7e00',
  vibrantGreen: '#3ecd83',
  // vibrantBlue: '#006aff', // #61afef
  vibrantBlue: '#61afef',
};

const statusColors = {
  success: '#10a273',
  error: '#c00c0c',
  warning: '#d2723b',
};

const workbenchColors = {
  backgroundActive: '#23386e',
  backgroundDrop: '#181420ce',
  backgroundEditor: '#1a212e',
  backgroundHeader: '#181420ce',
  backgroundHover: '#1a2950',
  backgroundHoverHighlight: '#dbdae82f',
  backgroundInactive: '#20283d',
  backgroundMatch: '#78e6c346',
  backgroundPopover: '#111520ee',
  backgroundSidebar: '#141b24',
  backgroundSelection: '#3a5599ac',
  foreground: '#dcbb',
};

const colors = {
  ...workbenchColors,
  ...vibrantColors,
  ...pastelColors,
  ...statusColors,
  ...ansiColors,
  // redLighter: '#fe5c57',
  // backgroundHeader: '#2a2749bd',
  // bgLight: '#21283b',
  greenSnazzy: '#5bf78e',
  // string: '#8acd5b',
  invisible: '#0000',
};

// foreground: '#ea31b5', #ff6ac1

const theme: ColorTheme = {
  name: 'Fullmetal',
  type: 'dark',
  colors: {
    'activityBar.background': colors.backgroundSidebar,
    'activityBar.activeBorder': colors.backgroundActive,
    'activityBar.foreground': colors.white,
    'badge.background': colors.yellow,
    'badge.foreground': colors.backgroundSidebar,
    'breadcrumb.activeSelectionForeground': colors.white,
    'breadcrumb.focusForeground': colors.gray,
    'breadcrumbPicker.background': colors.backgroundPopover,
    'button.background': colors.magenta,
    'dropdown.background': colors.backgroundSidebar,
    'editor.background': colors.backgroundEditor,
    'editor.findMatchHighlightBackground': '#e3e3e31f',
    'editor.findMatchHighlightBorder': colors.backgroundMatch,
    'editor.hoverHighlightBackground': colors.backgroundHoverHighlight,
    'editor.lineHighlightBackground': colors.backgroundInactive,
    'editor.symbolHighlightBackground': '#01c0ce45',
    'editor.symbolHighlightBorder': colors.orange,
    'editor.rangeHighlightBackground': '#01c0ce45',
    'editor.selectionBackground': colors.backgroundSelection,
    'editor.findMatchBackground': '',
    'editor.wordHighlightBackground': colors.backgroundHoverHighlight,
    'editorCursor.background': colors.backgroundEditor,
    'editorCursor.foreground': colors.white,
    'editorError.foreground': colors.error,
    'editorGroup.border': colors.backgroundSidebar,
    'editorGroup.dropBackground': colors.backgroundDrop,
    'editorGroupHeader.tabsBackground': colors.backgroundSidebar,
    'editorGutter.addedBackground': colors.success,
    'editorGutter.deletedBackground': colors.red,
    'editorGutter.foldingControlForeground': colors.gray,
    'editorGutter.modifiedBackground': colors.yellow,
    'editorHoverWidget.background': colors.backgroundPopover,
    'editorHoverWidget.border': colors.invisible,
    'editorLineNumber.activeForeground': colors.gray,
    'editorLineNumber.foreground': colors.pastelGray,
    'editorSuggestWidget.background': colors.backgroundPopover,
    'editorSuggestWidget.border': colors.invisible,
    'editorSuggestWidget.selectedIconForeground': colors.magenta,
    'errorLens.errorBackground': opacity(colors.error, 0.1),
    'errorLens.errorForeground': colors.error,
    'errorLens.warningBackground': opacity(colors.warning, 0.1),
    'errorLens.warningForeground': colors.warning,
    'extensionButton.prominentBackground': colors.success,
    'extensionButton.prominentForeground': colors.black,
    'extensionButton.prominentHoverBackground': colors.pastelGreen,
    'extensionIcon.preReleaseForeground': colors.warning,
    'extensionIcon.verifiedForeground': colors.pastelBlue,
    'extensionIcon.starForeground': colors.yellow,
    'gitDecoration.addedResourceForeground': colors.success,
    'gitDecoration.conflictingResourceForeground': colors.magenta,
    'gitDecoration.deletedResourceForeground': colors.red,
    'gitDecoration.ignoredResourceForeground': colors.pastelGray,
    'gitDecoration.modifiedResourceForeground': colors.yellow,
    'gitDecoration.renamedResourceForeground': colors.white,
    'gitDecoration.stageDeletedResourceForeground': colors.red,
    'gitDecoration.stageModifiedResourceForeground': colors.yellow,
    'gitDecoration.untrackedResourceForeground': colors.green,
    'focusBorder': colors.orange,
    'foreground': colors.foreground,
    'icon.foreground': colors.foreground,
    // 'icon.foreground': colors.gray,
    // 'input.background': '#2a314b',
    'input.background': colors.backgroundPopover,
    'input.foreground': colors.gray,
    'input.placeholderForeground': colors.pastelGray,
    'list.activeSelectionBackground': colors.backgroundActive,
    'list.activeSelectionForeground': colors.white,
    'list.deemphasizedForeground': colors.pastelGray,
    'list.dropBackground': colors.backgroundDrop,
    'list.errorForeground': colors.error,
    'list.filterMatchBackground': colors.backgroundMatch,
    'list.focusBackground': colors.backgroundHover,
    'list.focusForeground': colors.white,
    // 'list.focusHighlightForeground': colors.yellow,
    'list.highlightForeground': colors.green,
    'list.hoverBackground': colors.backgroundHover,
    'list.hoverForeground': colors.white,
    'list.inactiveFocusBackground': '#20283d69',
    'list.inactiveSelectionBackground': colors.backgroundInactive,
    'list.inactiveSelectionForeground': colors.gray,
    'list.invalidItemForeground': colors.error,
    'list.warningForeground': colors.orange,
    'listFilterWidget.background': '#283140',
    'listFilterWidget.noMatchesOutline': colors.error,
    'notificationCenterHeader.background': colors.backgroundPopover,
    'notifications.background': colors.backgroundPopover,
    'panel.border': colors.backgroundSidebar,
    'panelSectionHeader.background': colors.backgroundSidebar,
    'panelSectionHeader.foreground': colors.gray,
    'panelTitle.activeForeground': colors.gray,
    // 'panelTitle.inactiveForeground': colors.foreground,
    'quickInput.background': colors.backgroundPopover,
    'quickInputTitle.background': colors.backgroundPopover,
    'sash.hoverBorder': colors.yellow,
    'scrollbar.shadow': colors.invisible,
    'scrollbarSlider.activeBackground': opacity(colors.backgroundActive, 0.75), // '#23386ebb',
    'scrollbarSlider.background': '#25314dbb',
    'scrollbarSlider.hoverBackground': '#1a2950bb',
    'settings.modifiedItemIndicator': colors.yellow,
    'sideBar.background': colors.backgroundSidebar,
    'statusBar.background': colors.backgroundSidebar,
    'statusBar.foreground': colors.foreground,
    'statusBar.noFolderBackground': colors.backgroundSidebar,
    'statusBarItem.errorBackground': colors.error,
    'statusBarItem.hoverBackground': colors.backgroundHover,
    'statusBarItem.remoteBackground': colors.vibrantBlue, // '#3e79cd',
    'statusBarItem.warningBackground': colors.warning,
    'statusBar.debuggingBackground': colors.vibrantOrange,
    'statusBar.debuggingForeground': colors.backgroundSidebar,
    'tab.activeBackground': colors.backgroundEditor,
    'tab.activeBorder': colors.invisible,
    // 'tab.activeBorderTop': colors.backgroundActive,
    'tab.activeForeground': colors.gray,
    'tab.inactiveForeground': opacity(colors.gray, 0.6), // colors.foreground,
    'tab.activeModifiedBorder': colors.yellow,
    'tab.border': colors.invisible,
    'tab.hoverBackground': colors.backgroundHover,
    'tab.hoverForeground': colors.white,
    'tab.inactiveBackground': colors.backgroundSidebar,
    'tab.unfocusedActiveBorderTop': colors.invisible,
    'textLink.foreground': colors.blue,
    'textLink.activeForeground': colors.vibrantBlue,
    'titleBar.activeBackground': colors.backgroundSidebar,
    'titleBar.activeForeground': colors.foreground,
    'titleBar.inactiveBackground': colors.backgroundEditor,
    'tree.indentGuidesStroke': colors.pastelGray,
    'widget.shadow': '#0c0e1554',
    'editorWidget.background': colors.backgroundPopover,
    'editorWidget.border': colors.backgroundActive,
    'editorLightBulb.foreground': colors.yellow,
    'editorBracketHighlight.unexpectedBracket.foreground': colors.error,
    // 'sideBarSectionHeader.background': colors.backgroundSidebar,
    'sideBarSectionHeader.background': colors.backgroundSidebar, // opacity(colors.backgroundEditor, 0.5),
    'sideBarSectionHeader.foreground': colors.gray,
    // 'editorBracketHighlight.foreground1': '#fe5c57',
    // "editor.wordHighlightBorder": "#78e6c3",
    // "editorGutter.addedBackground": "#5bf78e",
    // "editorSuggestWidget.border": "#23386e",
    // "editorSuggestWidget.border": "",
    // "editorSuggestWidget.border": "#dd9046",
    // "list.activeSelectionBackground": "#1a2950",
    // 'list.dropBackground': '#6d0b2c8a',
    // "list.filterMatchBackground": "",
    // "list.filterMatchBackground": "#e98d8f94",
    // "list.filterMatchBorder": "",
    // "list.filterMatchBorder": "#78e6c3",
    // "list.hoverBackground": "#23386e",
    // "notifications.background": "#283140",
    // "panel.background": "",
    // "panel.border": "#0c0e15",
    // "panelTitle.activeBorder": "",
    // "panelTitle.activeForeground": "",
    // "panelTitle.inactiveForeground": "",
    // "quickInput.background": "#0b1115",
    // "quickInput.background": "#141b24e0",
    // "scrollbarSlider.background": "#20283d",
    // "scrollbarSlider.background": "#322e40",
    // "sideBar.border": "#0c0e15",
    // "statusBarItem.remoteBackground": "",
    // "statusBarItem.remoteForeground": "#dcbb",
    // "tab.inactiveBackground": "#21283b",
    'editorLink.activeForeground': colors.blue,
    'editorCodeLens.foreground': colors.pastelGray,
    'editorBracketHighlight.foreground1': '#c75ae8',
    'editorBracketHighlight.foreground2': colors.cyan,
    'editorBracketHighlight.foreground3': '#f6b868',
    // 'editorBracketHighlight.foreground4': colors.pastelGreen,
    'editor.foreground': colors.gray,
    'editorInlayHint.background': '#253c7a70',
    'editorInlayHint.foreground': colors.pastelGreen,
    'terminal.ansiGreen': colors.green,
    'terminal.ansiBlack': colors.black,
    'terminal.ansiBlue': colors.blue,
    'terminal.ansiRed': colors.red,
    'terminal.ansiWhite': colors.white,
    'terminal.ansiYellow': colors.yellow,
    'terminal.ansiMagenta': colors.magenta,
    'terminal.ansiCyan': colors.cyan,
    'terminal.ansiBrightGreen': colors.vibrantGreen,
    'terminalCursor.background': colors.backgroundEditor,
    'terminalCursor.foreground': colors.white,
    'terminal.selectionBackground': colors.backgroundSelection,
  },
  semanticHighlighting: true,
  semanticTokenColors: {
    'keyword.unsafe': colors.red,
    'macro': {
      fontStyle: 'italic',
    },
    'macroBang': {
      fontStyle: 'italic',
    },
    // '*.readonly': {
    //   fontStyle: 'underline',
    // },
  },
  tokenColors: [
    {
      name: 'keywords',
      scope: [
        specificity('source', 'keyword.other'),
        specificity('source', 'keyword.control'),
        'keyword.operator.new',
        'keyword.declaration',
        'support.type.object.module',
        'variable.language.self',
        'variable.language.super',
        'variable.language.this',
      ],
      settings: {
        foreground: colors.magenta,
      },
    },
    {
      name: 'storage keyword (e.g. mod)',
      scope: 'storage.type',
      settings: {
        foreground: colors.magenta,
      },
    },
    {
      name: 'storage modifier (e.g. mut)',
      scope: 'storage.modifier',
      settings: {
        foreground: colors.vibrantOrange,
        // foreground: '#f6b868',
      },
    },
    {
      name: 'attributes',
      scope: specificity('source', 'meta.attribute'),
      settings: {
        foreground: colors.blue,
      },
    },
    {
      name: 'string',
      scope: [
        'string',
        'support.constant.property-value',
        'punctuation.definition.string',
        'punctuation.definition.char',
      ],
      settings: {
        foreground: colors.green,
      },
    },
    {
      name: 'escape character',
      scope: [
        'constant.character.escape',
        'punctuation.definition.template-expression.begin',
        'keyword.operator.logical',
      ],
      settings: {
        foreground: colors.red,
      },
    },
    {
      name: 'comments',
      scope: ['comment.line', 'comment.block', 'punctuation.definition.comment'],
      settings: {
        fontStyle: 'italic',
        foreground: colors.pastelGray,
      },
    },
    {
      name: 'markdown code blocks',
      scope: ['markup.fenced_code.block', 'markup.inline.raw'],
      settings: {
        foreground: colors.pastelGray,
      },
    },
    {
      name: 'bold',
      scope: ['punctuation.definition.heading'],
      settings: {
        fontStyle: 'bold',
      },
    },
    {
      name: 'unlabelled source',
      scope: ['meta.paragraph.markdown', 'source.ignore'],
      settings: {
        foreground: colors.foreground,
      },
    },
    {
      name: 'variable declaration and parameters',
      scope: ['variable.other', 'variable.parameter', 'variable.key.table'],
      settings: {
        foreground: colors.pastelBlue,
        // foreground: '#d6b792',
        // foreground: '#f6b868',
        // foreground: '#c75ae8',
      },
    },
    {
      name: 'struct/object properties',
      scope: [
        'variable.other.property',
        'variable.other.object.property',
        'support.type.property-name',
        'support.resource.attribute',
        'entity.other.attribute-name',
        'punctuation.support.type.property-name',
        'variable.key',
      ],
      settings: {
        foreground: colors.violet,
        // foreground: '#ba92d6',
        // foreground: colors.pastelGreen,
        // "foreground": "#01c0ce"
      },
    },
    {
      name: 'function',
      scope: ['entity.name.function', 'support.function', 'markup.underline.link'],
      settings: {
        foreground: colors.blue,
      },
    },
    {
      name: 'booleans, constants',
      scope: ['constant.language.boolean', 'constant.language', 'support.constant'],
      settings: {
        foreground: colors.orange,
      },
    },
    {
      name: 'type definition',
      scope: ['entity.name', 'support.class.console'],
      settings: {
        foreground: colors.yellow,
      },
    },
    {
      name: 'number',
      scope: ['constant.numeric', 'punctuation.definition.list.begin'],
      settings: {
        foreground: colors.orange,
      },
    },
    {
      name: 'punctuation',
      scope: 'punctuation',
      settings: {
        foreground: colors.cyan,
        // foreground: colors.gray,
        // foreground: '#ab725e',
      },
    },
    {
      name: 'assignment operator (=)',
      scope: ['keyword.operator.assignment', 'keyword.operator.access.dot'],
      settings: {
        // foreground: colors.pastelGreen,
        foreground: colors.cyan,
        // foreground: '#f6b868',
        // foreground: '#FDBAA6',
      },
    },
    {
      name: 'arrow ->',
      scope: 'keyword.operator.arrow.skinny',
      settings: {
        // foreground: '#5bf78e',
        foreground: colors.cyan,
      },
    },
  ],
};

// Generate color theme json file
fs.writeFileSync(
  path.join(process.cwd(), 'themes', 'fullmetal-color-theme.json'),
  JSON.stringify(theme, null, 2)
);
