import fs from 'fs';
import path from 'path';
import type {ColorTheme} from '..';

const colors = {
  // potential green alternative: '#3ecd83'
  // redLighter: '#fe5c57',
  backgroundActive: '#23386e',
  backgroundDrop: '#181420ce',
  backgroundEditor: '#1a212e',
  // backgroundHeader: '#2a2749bd',
  backgroundHeader: '#181420ce',
  backgroundHover: '#1a2950',
  backgroundInactive: '#20283d',
  backgroundMatch: '#78e6c346',
  backgroundPopover: '#111520ee',
  backgroundSidebar: '#141b24',
  bgLight: '#21283b',
  black: '#0c0e15',
  blue: '#41a7fc',
  error: '#c00c0c',
  foreground: '#dcbb',
  gray: '#90a5c8',
  grayFade: '#455573',
  greenSnazzy: '#5bf78e',
  orange: '#dd9046',
  red: '#ff4762',
  string: '#8acd5b',
  success: '#10a273',
  white: '#dbdae8',
  yellow: '#efbd5d',
  invisible: '#0000',
};

const theme: ColorTheme = {
  name: 'Fullmetal',
  type: 'dark',
  colors: {
    'badge.background': colors.yellow,
    'badge.foreground': colors.backgroundSidebar,
    'breadcrumb.activeSelectionForeground': colors.white,
    'breadcrumb.focusForeground': colors.gray,
    'breadcrumbPicker.background': colors.backgroundPopover,
    // 'breadcrumbPicker.background': '#21283b',
    'button.background': '#ec59e7',
    'dropdown.background': colors.backgroundSidebar,
    'editor.background': colors.backgroundEditor,
    'editor.findMatchHighlightBackground': '#e3e3e31f',
    'editor.findMatchHighlightBorder': colors.backgroundMatch,
    'editor.hoverHighlightBackground': '#dbdae82f',
    'editor.lineHighlightBackground': colors.backgroundInactive,
    'editor.symbolHighlightBackground': '',
    'editor.symbolHighlightBorder': '',
    'editor.rangeHighlightBackground': '',
    'editor.selectionBackground': '#23386ead',
    'editor.wordHighlightBackground': '#dbdae82f',
    'editorCursor.background': colors.backgroundEditor,
    'editorCursor.foreground': '#fff',
    'editorError.foreground': colors.error,
    'editorGroup.border': colors.backgroundSidebar,
    'editorGroup.dropBackground': colors.backgroundDrop,
    'editorGroupHeader.tabsBackground': colors.backgroundSidebar,
    'editorGutter.addedBackground': colors.success,
    'editorGutter.deletedBackground': colors.red,
    'editorGutter.foldingControlForeground': colors.gray,
    'editorGutter.modifiedBackground': colors.yellow,
    'editorHoverWidget.background': colors.backgroundPopover,
    'editorHoverWidget.border': colors.invisible,
    'editorLineNumber.activeForeground': colors.gray,
    'editorLineNumber.foreground': colors.grayFade,
    'editorSuggestWidget.background': colors.backgroundPopover,
    'editorSuggestWidget.border': colors.invisible,
    'errorLens.errorBackground': '#3a1d28',
    'errorLens.errorForeground': colors.error,
    'gitDecoration.addedResourceForeground': colors.success,
    'gitDecoration.conflictingResourceForeground': '#ff6ac1',
    'gitDecoration.deletedResourceForeground': colors.red,
    'gitDecoration.ignoredResourceForeground': colors.grayFade,
    'gitDecoration.modifiedResourceForeground': colors.yellow,
    'gitDecoration.renamedResourceForeground': colors.white,
    'gitDecoration.stageDeletedResourceForeground': colors.red,
    'gitDecoration.stageModifiedResourceForeground': colors.yellow,
    'gitDecoration.untrackedResourceForeground': colors.string,
    'focusBorder': colors.orange,
    'foreground': colors.foreground,
    'icon.foreground': colors.foreground,
    // 'icon.foreground': colors.gray,
    'input.background': colors.backgroundSidebar,
    'list.activeSelectionBackground': colors.backgroundActive,
    'list.activeSelectionForeground': colors.white,
    'list.deemphasizedForeground': colors.grayFade,
    'list.dropBackground': colors.backgroundDrop,
    'list.errorForeground': colors.error,
    'list.filterMatchBackground': colors.backgroundMatch,
    'list.focusBackground': colors.backgroundHover,
    'list.focusForeground': colors.white,
    // 'list.focusHighlightForeground': colors.yellow,
    'list.highlightForeground': colors.string,
    'list.hoverBackground': colors.backgroundHover,
    'list.hoverForeground': colors.white,
    'list.inactiveFocusBackground': '#20283d69',
    'list.inactiveSelectionBackground': colors.backgroundInactive,
    'list.inactiveSelectionForeground': colors.gray,
    'list.invalidItemForeground': colors.error,
    'list.warningForeground': colors.orange,
    'listFilterWidget.background': '#283140',
    'listFilterWidget.noMatchesOutline': colors.error,
    'notificationCenterHeader.background': colors.backgroundHeader,
    'notifications.background': colors.backgroundPopover,
    'panel.border': colors.backgroundSidebar,
    'panelSectionHeader.background': colors.backgroundSidebar,
    'panelTitle.activeForeground': colors.gray,
    'quickInput.background': colors.backgroundPopover,
    'quickInputTitle.background': colors.backgroundHeader,
    'sash.hoverBorder': colors.yellow,
    'scrollbar.shadow': colors.invisible,
    'scrollbarSlider.activeBackground': '#23386ebb',
    'scrollbarSlider.background': '#25314dbb',
    'scrollbarSlider.hoverBackground': '#1a2950bb',
    'settings.modifiedItemIndicator': colors.yellow,
    'sideBar.background': colors.backgroundSidebar,
    'statusBar.background': colors.backgroundSidebar,
    'statusBar.foreground': colors.foreground,
    'statusBarItem.remoteBackground': '#3e79cd',
    'tab.activeBackground': colors.backgroundEditor,
    'tab.activeBorder': colors.invisible,
    // 'tab.activeBorderTop': colors.backgroundActive,
    'tab.activeForeground': colors.gray,
    'tab.activeModifiedBorder': colors.yellow,
    'tab.border': colors.invisible,
    'tab.hoverBackground': colors.backgroundHover,
    'tab.hoverForeground': colors.white,
    'tab.inactiveBackground': colors.backgroundSidebar,
    'tab.unfocusedActiveBorderTop': colors.invisible,
    'textLink.foreground': '#3e79cd',
    'titleBar.activeBackground': colors.backgroundSidebar,
    'titleBar.activeForeground': colors.foreground,
    'titleBar.inactiveBackground': colors.backgroundEditor,
    'tree.indentGuidesStroke': colors.gray,
    'widget.shadow': '#0c0e1554',
    'editorWidget.background': colors.backgroundPopover,
    'editorWidget.border': colors.backgroundActive,
    'editorLightBulb.foreground': colors.yellow,
    // 'editorBracketHighlight.foreground1': '#fe5c57',
    // "editor.wordHighlightBorder": "#78e6c3",
    // "editorGutter.addedBackground": "#5bf78e",
    // "editorSuggestWidget.border": "#23386e",
    // "editorSuggestWidget.border": "#61afef",
    // "editorSuggestWidget.border": "#dd9046",
    // "list.activeSelectionBackground": "#1a2950",
    // 'list.dropBackground': '#6d0b2c8a',
    // "list.filterMatchBackground": "",
    // "list.filterMatchBackground": "#e98d8f94",
    // "list.filterMatchBorder": "",
    // "list.filterMatchBorder": "#78e6c3",
    // "list.hoverBackground": "#23386e",
    // "notifications.background": "#283140",
    // "panel.background": "",
    // "panel.border": "#0c0e15",
    // "panelTitle.activeBorder": "",
    // "panelTitle.activeForeground": "",
    // "panelTitle.inactiveForeground": "",
    // "quickInput.background": "#0b1115",
    // "quickInput.background": "#141b24e0",
    // "scrollbarSlider.background": "#20283d",
    // "scrollbarSlider.background": "#322e40",
    // "sideBar.border": "#0c0e15",
    // "statusBarItem.remoteBackground": "#41a7fc",
    // "statusBarItem.remoteForeground": "#dcbb",
    // "tab.inactiveBackground": "#21283b",
    // "textLink.activeForeground"
    // "titleBar.border": "#0c0e15",
    // 'editorBracketPairGuide.activeBackground1': '#c75ae8',
    'editorBracketHighlight.foreground1': '#c75ae8',
    'editorBracketHighlight.foreground2': '#add692',
    // 'editorBracketPairGuide.activeBackground2': ,
  },
  semanticHighlighting: true,
  semanticTokenColors: {
    'keyword.unsafe': colors.red,
  },
  tokenColors: [
    {
      name: 'keyword',
      scope: 'keyword',
      settings: {
        foreground: '#d44dae',
        // foreground: '#ea31b5',
      },
    },
    {
      name: 'string',
      scope: 'string',
      settings: {
        foreground: colors.string,
      },
    },
    {
      name: 'escape character',
      scope: 'constant.character.escape',
      settings: {
        foreground: colors.red,
      },
    },
    {
      name: 'character',
      scope: 'string.quoted.single.char',
      settings: {
        foreground: '#add692',
      },
    },
    {
      name: 'line comment',
      scope: 'comment.line',
      settings: {
        fontStyle: 'bold',
        foreground: colors.grayFade,
      },
    },
    {
      name: 'variable declaration and parameters',
      scope: 'variable.other',
      settings: {
        foreground: '#92d6cf',
        // foreground: '#d6b792',
        // foreground: '#f6b868',
        // foreground: '#c75ae8',
      },
    },
    {
      name: 'struct/object properties',
      scope: 'variable.other.property',
      settings: {
        foreground: '#ba92d6',
        // foreground: '#add692',
        // "foreground": "#61afef"
        // "foreground": "#01c0ce"
        // foreground: '#3dacb4',
        // foreground: '#92d6cf',
      },
    },
    {
      name: 'function',
      scope: 'entity.name.function',
      settings: {
        foreground: '#61afef',
      },
    },
    {
      name: 'boolean',
      scope: 'constant.language.boolean',
      settings: {
        foreground: colors.orange,
      },
    },
    {
      name: 'type definition',
      scope: 'entity.name.type',
      settings: {
        // foreground: colors.orange,
        foreground: colors.yellow,
      },
    },
    {
      name: 'number',
      scope: 'constant.numeric',
      settings: {
        foreground: colors.orange,
      },
    },
    {
      name: 'punctuation',
      scope: 'punctuation',
      settings: {
        foreground: colors.gray,
        // foreground: '#ab725e',
      },
    },
    {
      name: 'operator',
      scope: 'keyword.operator',
      settings: {
        foreground: '#FDBAA6',
      },
    },
  ],
};

// Generate color theme json file
fs.writeFileSync(
  path.join(process.cwd(), 'themes', 'fullmetal-color-theme.json'),
  JSON.stringify(theme, null, 2)
);
