/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Colors for syntax highlighting
 */
export type TextmateColors = {
  /**
   * Description of the rule.
   */
  name?: string;
  /**
   * Scope selector against which this rule matches.
   */
  scope?:
    | (
        | "comment"
        | "comment.block"
        | "comment.block.documentation"
        | "comment.line"
        | "constant"
        | "constant.character"
        | "constant.character.escape"
        | "constant.numeric"
        | "constant.numeric.integer"
        | "constant.numeric.float"
        | "constant.numeric.hex"
        | "constant.numeric.octal"
        | "constant.other"
        | "constant.regexp"
        | "constant.rgb-value"
        | "emphasis"
        | "entity"
        | "entity.name"
        | "entity.name.class"
        | "entity.name.function"
        | "entity.name.method"
        | "entity.name.section"
        | "entity.name.selector"
        | "entity.name.tag"
        | "entity.name.type"
        | "entity.other"
        | "entity.other.attribute-name"
        | "entity.other.inherited-class"
        | "invalid"
        | "invalid.deprecated"
        | "invalid.illegal"
        | "keyword"
        | "keyword.control"
        | "keyword.operator"
        | "keyword.operator.new"
        | "keyword.operator.assignment"
        | "keyword.operator.arithmetic"
        | "keyword.operator.logical"
        | "keyword.other"
        | "markup"
        | "markup.bold"
        | "markup.changed"
        | "markup.deleted"
        | "markup.heading"
        | "markup.inline.raw"
        | "markup.inserted"
        | "markup.italic"
        | "markup.list"
        | "markup.list.numbered"
        | "markup.list.unnumbered"
        | "markup.other"
        | "markup.quote"
        | "markup.raw"
        | "markup.underline"
        | "markup.underline.link"
        | "meta"
        | "meta.block"
        | "meta.cast"
        | "meta.class"
        | "meta.function"
        | "meta.function-call"
        | "meta.preprocessor"
        | "meta.return-type"
        | "meta.selector"
        | "meta.tag"
        | "meta.type.annotation"
        | "meta.type"
        | "punctuation.definition.string.begin"
        | "punctuation.definition.string.end"
        | "punctuation.separator"
        | "punctuation.separator.continuation"
        | "punctuation.terminator"
        | "storage"
        | "storage.modifier"
        | "storage.type"
        | "string"
        | "string.interpolated"
        | "string.other"
        | "string.quoted"
        | "string.quoted.double"
        | "string.quoted.other"
        | "string.quoted.single"
        | "string.quoted.triple"
        | "string.regexp"
        | "string.unquoted"
        | "strong"
        | "support"
        | "support.class"
        | "support.constant"
        | "support.function"
        | "support.other"
        | "support.type"
        | "support.type.property-name"
        | "support.variable"
        | "variable"
        | "variable.language"
        | "variable.name"
        | "variable.other"
        | "variable.other.readwrite"
        | "variable.parameter"
      )
    | string
    | (
        | "comment"
        | "comment.block"
        | "comment.block.documentation"
        | "comment.line"
        | "constant"
        | "constant.character"
        | "constant.character.escape"
        | "constant.numeric"
        | "constant.numeric.integer"
        | "constant.numeric.float"
        | "constant.numeric.hex"
        | "constant.numeric.octal"
        | "constant.other"
        | "constant.regexp"
        | "constant.rgb-value"
        | "emphasis"
        | "entity"
        | "entity.name"
        | "entity.name.class"
        | "entity.name.function"
        | "entity.name.method"
        | "entity.name.section"
        | "entity.name.selector"
        | "entity.name.tag"
        | "entity.name.type"
        | "entity.other"
        | "entity.other.attribute-name"
        | "entity.other.inherited-class"
        | "invalid"
        | "invalid.deprecated"
        | "invalid.illegal"
        | "keyword"
        | "keyword.control"
        | "keyword.operator"
        | "keyword.operator.new"
        | "keyword.operator.assignment"
        | "keyword.operator.arithmetic"
        | "keyword.operator.logical"
        | "keyword.other"
        | "markup"
        | "markup.bold"
        | "markup.changed"
        | "markup.deleted"
        | "markup.heading"
        | "markup.inline.raw"
        | "markup.inserted"
        | "markup.italic"
        | "markup.list"
        | "markup.list.numbered"
        | "markup.list.unnumbered"
        | "markup.other"
        | "markup.quote"
        | "markup.raw"
        | "markup.underline"
        | "markup.underline.link"
        | "meta"
        | "meta.block"
        | "meta.cast"
        | "meta.class"
        | "meta.function"
        | "meta.function-call"
        | "meta.preprocessor"
        | "meta.return-type"
        | "meta.selector"
        | "meta.tag"
        | "meta.type.annotation"
        | "meta.type"
        | "punctuation.definition.string.begin"
        | "punctuation.definition.string.end"
        | "punctuation.separator"
        | "punctuation.separator.continuation"
        | "punctuation.terminator"
        | "storage"
        | "storage.modifier"
        | "storage.type"
        | "string"
        | "string.interpolated"
        | "string.other"
        | "string.quoted"
        | "string.quoted.double"
        | "string.quoted.other"
        | "string.quoted.single"
        | "string.quoted.triple"
        | "string.regexp"
        | "string.unquoted"
        | "strong"
        | "support"
        | "support.class"
        | "support.constant"
        | "support.function"
        | "support.other"
        | "support.type"
        | "support.type.property-name"
        | "support.variable"
        | "variable"
        | "variable.language"
        | "variable.name"
        | "variable.other"
        | "variable.other.readwrite"
        | "variable.parameter"
      )[]
    | string[];
  settings: Settings;
}[];

export interface ColorTheme {
  colors?: WorkbenchColors;
  tokenColors?: string | TextmateColors;
  /**
   * Whether semantic highlighting should be enabled for this theme.
   */
  semanticHighlighting?: boolean;
  semanticTokenColors?: TokenStyling;
  [k: string]: unknown;
}
/**
 * Colors in the workbench
 */
export interface WorkbenchColors {
  foreground?: string | "default";
  disabledForeground?: string | "default";
  errorForeground?: string | "default";
  descriptionForeground?: string | "default";
  "icon.foreground"?: string | "default";
  focusBorder?: string | "default";
  contrastBorder?: string | "default";
  contrastActiveBorder?: string | "default";
  "selection.background"?: string | "default";
  "textLink.foreground"?: string | "default";
  "textLink.activeForeground"?: string | "default";
  "textSeparator.foreground"?: string | "default";
  "textPreformat.foreground"?: string | "default";
  "textPreformat.background"?: string | "default";
  "textBlockQuote.background"?: string | "default";
  "textBlockQuote.border"?: string | "default";
  "textCodeBlock.background"?: string | "default";
  "sash.hoverBorder"?: string | "default";
  "badge.background"?: string | "default";
  "badge.foreground"?: string | "default";
  "scrollbar.shadow"?: string | "default";
  "scrollbarSlider.background"?: string | "default";
  "scrollbarSlider.hoverBackground"?: string | "default";
  "scrollbarSlider.activeBackground"?: string | "default";
  "progressBar.background"?: string | "default";
  "editor.background"?: string | "default";
  "editor.foreground"?: string | "default";
  "editorStickyScroll.background"?: string | "default";
  "editorStickyScrollHover.background"?: string | "default";
  "editorStickyScroll.border"?: string | "default";
  "editorStickyScroll.shadow"?: string | "default";
  "editorWidget.background"?: string | "default";
  "editorWidget.foreground"?: string | "default";
  "editorWidget.border"?: string | "default";
  "editorWidget.resizeBorder"?: string | "default";
  "editorError.background"?: string | "default";
  "editorError.foreground"?: string | "default";
  "editorError.border"?: string | "default";
  "editorWarning.background"?: string | "default";
  "editorWarning.foreground"?: string | "default";
  "editorWarning.border"?: string | "default";
  "editorInfo.background"?: string | "default";
  "editorInfo.foreground"?: string | "default";
  "editorInfo.border"?: string | "default";
  "editorHint.foreground"?: string | "default";
  "editorHint.border"?: string | "default";
  "editorLink.activeForeground"?: string | "default";
  "editor.selectionBackground"?: string | "default";
  "editor.selectionForeground"?: string | "default";
  "editor.inactiveSelectionBackground"?: string | "default";
  "editor.selectionHighlightBackground"?: string | "default";
  "editor.selectionHighlightBorder"?: string | "default";
  "editor.findMatchBackground"?: string | "default";
  "editor.findMatchForeground"?: string | "default";
  "editor.findMatchHighlightBackground"?: string | "default";
  "editor.findMatchHighlightForeground"?: string | "default";
  "editor.findRangeHighlightBackground"?: string | "default";
  "editor.findMatchBorder"?: string | "default";
  "editor.findMatchHighlightBorder"?: string | "default";
  "editor.findRangeHighlightBorder"?: string | "default";
  "editor.hoverHighlightBackground"?: string | "default";
  "editorHoverWidget.background"?: string | "default";
  "editorHoverWidget.foreground"?: string | "default";
  "editorHoverWidget.border"?: string | "default";
  "editorHoverWidget.statusBarBackground"?: string | "default";
  "editorInlayHint.foreground"?: string | "default";
  "editorInlayHint.background"?: string | "default";
  "editorInlayHint.typeForeground"?: string | "default";
  "editorInlayHint.typeBackground"?: string | "default";
  "editorInlayHint.parameterForeground"?: string | "default";
  "editorInlayHint.parameterBackground"?: string | "default";
  "editorLightBulb.foreground"?: string | "default";
  "editorLightBulbAutoFix.foreground"?: string | "default";
  "editorLightBulbAi.foreground"?: string | "default";
  "editor.snippetTabstopHighlightBackground"?: string | "default";
  "editor.snippetTabstopHighlightBorder"?: string | "default";
  "editor.snippetFinalTabstopHighlightBackground"?: string | "default";
  "editor.snippetFinalTabstopHighlightBorder"?: string | "default";
  "diffEditor.insertedTextBackground"?: string | "default";
  "diffEditor.removedTextBackground"?: string | "default";
  "diffEditor.insertedLineBackground"?: string | "default";
  "diffEditor.removedLineBackground"?: string | "default";
  "diffEditorGutter.insertedLineBackground"?: string | "default";
  "diffEditorGutter.removedLineBackground"?: string | "default";
  "diffEditorOverview.insertedForeground"?: string | "default";
  "diffEditorOverview.removedForeground"?: string | "default";
  "diffEditor.insertedTextBorder"?: string | "default";
  "diffEditor.removedTextBorder"?: string | "default";
  "diffEditor.border"?: string | "default";
  "diffEditor.diagonalFill"?: string | "default";
  "diffEditor.unchangedRegionBackground"?: string | "default";
  "diffEditor.unchangedRegionForeground"?: string | "default";
  "diffEditor.unchangedCodeBackground"?: string | "default";
  "widget.shadow"?: string | "default";
  "widget.border"?: string | "default";
  "toolbar.hoverBackground"?: string | "default";
  "toolbar.hoverOutline"?: string | "default";
  "toolbar.activeBackground"?: string | "default";
  "breadcrumb.foreground"?: string | "default";
  "breadcrumb.background"?: string | "default";
  "breadcrumb.focusForeground"?: string | "default";
  "breadcrumb.activeSelectionForeground"?: string | "default";
  "breadcrumbPicker.background"?: string | "default";
  "merge.currentHeaderBackground"?: string | "default";
  "merge.currentContentBackground"?: string | "default";
  "merge.incomingHeaderBackground"?: string | "default";
  "merge.incomingContentBackground"?: string | "default";
  "merge.commonHeaderBackground"?: string | "default";
  "merge.commonContentBackground"?: string | "default";
  "merge.border"?: string | "default";
  "editorOverviewRuler.currentContentForeground"?: string | "default";
  "editorOverviewRuler.incomingContentForeground"?: string | "default";
  "editorOverviewRuler.commonContentForeground"?: string | "default";
  "editorOverviewRuler.findMatchForeground"?: string | "default";
  "editorOverviewRuler.selectionHighlightForeground"?: string | "default";
  "problemsErrorIcon.foreground"?: string | "default";
  "problemsWarningIcon.foreground"?: string | "default";
  "problemsInfoIcon.foreground"?: string | "default";
  "input.background"?: string | "default";
  "input.foreground"?: string | "default";
  "input.border"?: string | "default";
  "inputOption.activeBorder"?: string | "default";
  "inputOption.hoverBackground"?: string | "default";
  "inputOption.activeBackground"?: string | "default";
  "inputOption.activeForeground"?: string | "default";
  "input.placeholderForeground"?: string | "default";
  "inputValidation.infoBackground"?: string | "default";
  "inputValidation.infoForeground"?: string | "default";
  "inputValidation.infoBorder"?: string | "default";
  "inputValidation.warningBackground"?: string | "default";
  "inputValidation.warningForeground"?: string | "default";
  "inputValidation.warningBorder"?: string | "default";
  "inputValidation.errorBackground"?: string | "default";
  "inputValidation.errorForeground"?: string | "default";
  "inputValidation.errorBorder"?: string | "default";
  "dropdown.background"?: string | "default";
  "dropdown.listBackground"?: string | "default";
  "dropdown.foreground"?: string | "default";
  "dropdown.border"?: string | "default";
  "button.foreground"?: string | "default";
  "button.separator"?: string | "default";
  "button.background"?: string | "default";
  "button.hoverBackground"?: string | "default";
  "button.border"?: string | "default";
  "button.secondaryForeground"?: string | "default";
  "button.secondaryBackground"?: string | "default";
  "button.secondaryHoverBackground"?: string | "default";
  "checkbox.background"?: string | "default";
  "checkbox.selectBackground"?: string | "default";
  "checkbox.foreground"?: string | "default";
  "checkbox.border"?: string | "default";
  "checkbox.selectBorder"?: string | "default";
  "keybindingLabel.background"?: string | "default";
  "keybindingLabel.foreground"?: string | "default";
  "keybindingLabel.border"?: string | "default";
  "keybindingLabel.bottomBorder"?: string | "default";
  "list.focusBackground"?: string | "default";
  "list.focusForeground"?: string | "default";
  "list.focusOutline"?: string | "default";
  "list.focusAndSelectionOutline"?: string | "default";
  "list.activeSelectionBackground"?: string | "default";
  "list.activeSelectionForeground"?: string | "default";
  "list.activeSelectionIconForeground"?: string | "default";
  "list.inactiveSelectionBackground"?: string | "default";
  "list.inactiveSelectionForeground"?: string | "default";
  "list.inactiveSelectionIconForeground"?: string | "default";
  "list.inactiveFocusBackground"?: string | "default";
  "list.inactiveFocusOutline"?: string | "default";
  "list.hoverBackground"?: string | "default";
  "list.hoverForeground"?: string | "default";
  "list.dropBackground"?: string | "default";
  "list.dropBetweenBackground"?: string | "default";
  "list.highlightForeground"?: string | "default";
  "list.focusHighlightForeground"?: string | "default";
  "list.invalidItemForeground"?: string | "default";
  "list.errorForeground"?: string | "default";
  "list.warningForeground"?: string | "default";
  "listFilterWidget.background"?: string | "default";
  "listFilterWidget.outline"?: string | "default";
  "listFilterWidget.noMatchesOutline"?: string | "default";
  "listFilterWidget.shadow"?: string | "default";
  "list.filterMatchBackground"?: string | "default";
  "list.filterMatchBorder"?: string | "default";
  "list.deemphasizedForeground"?: string | "default";
  "tree.indentGuidesStroke"?: string | "default";
  "tree.inactiveIndentGuidesStroke"?: string | "default";
  "tree.tableColumnsBorder"?: string | "default";
  "tree.tableOddRowsBackground"?: string | "default";
  "menu.border"?: string | "default";
  "menu.foreground"?: string | "default";
  "menu.background"?: string | "default";
  "menu.selectionForeground"?: string | "default";
  "menu.selectionBackground"?: string | "default";
  "menu.selectionBorder"?: string | "default";
  "menu.separatorBackground"?: string | "default";
  "minimap.findMatchHighlight"?: string | "default";
  "minimap.selectionOccurrenceHighlight"?: string | "default";
  "minimap.selectionHighlight"?: string | "default";
  "minimap.infoHighlight"?: string | "default";
  "minimap.warningHighlight"?: string | "default";
  "minimap.errorHighlight"?: string | "default";
  "minimap.background"?: string | "default";
  "minimap.foregroundOpacity"?: string | "default";
  "minimapSlider.background"?: string | "default";
  "minimapSlider.hoverBackground"?: string | "default";
  "minimapSlider.activeBackground"?: string | "default";
  "charts.foreground"?: string | "default";
  "charts.lines"?: string | "default";
  "charts.red"?: string | "default";
  "charts.blue"?: string | "default";
  "charts.yellow"?: string | "default";
  "charts.orange"?: string | "default";
  "charts.green"?: string | "default";
  "charts.purple"?: string | "default";
  "quickInput.background"?: string | "default";
  "quickInput.foreground"?: string | "default";
  "quickInputTitle.background"?: string | "default";
  "pickerGroup.foreground"?: string | "default";
  "pickerGroup.border"?: string | "default";
  "quickInput.list.focusBackground"?: string | "default";
  "quickInputList.focusForeground"?: string | "default";
  "quickInputList.focusIconForeground"?: string | "default";
  "quickInputList.focusBackground"?: string | "default";
  "search.resultsInfoForeground"?: string | "default";
  "searchEditor.findMatchBackground"?: string | "default";
  "searchEditor.findMatchBorder"?: string | "default";
  "multiDiffEditor.headerBackground"?: string | "default";
  "multiDiffEditor.background"?: string | "default";
  "multiDiffEditor.border"?: string | "default";
  "symbolIcon.arrayForeground"?: string | "default";
  "symbolIcon.booleanForeground"?: string | "default";
  "symbolIcon.classForeground"?: string | "default";
  "symbolIcon.colorForeground"?: string | "default";
  "symbolIcon.constantForeground"?: string | "default";
  "symbolIcon.constructorForeground"?: string | "default";
  "symbolIcon.enumeratorForeground"?: string | "default";
  "symbolIcon.enumeratorMemberForeground"?: string | "default";
  "symbolIcon.eventForeground"?: string | "default";
  "symbolIcon.fieldForeground"?: string | "default";
  "symbolIcon.fileForeground"?: string | "default";
  "symbolIcon.folderForeground"?: string | "default";
  "symbolIcon.functionForeground"?: string | "default";
  "symbolIcon.interfaceForeground"?: string | "default";
  "symbolIcon.keyForeground"?: string | "default";
  "symbolIcon.keywordForeground"?: string | "default";
  "symbolIcon.methodForeground"?: string | "default";
  "symbolIcon.moduleForeground"?: string | "default";
  "symbolIcon.namespaceForeground"?: string | "default";
  "symbolIcon.nullForeground"?: string | "default";
  "symbolIcon.numberForeground"?: string | "default";
  "symbolIcon.objectForeground"?: string | "default";
  "symbolIcon.operatorForeground"?: string | "default";
  "symbolIcon.packageForeground"?: string | "default";
  "symbolIcon.propertyForeground"?: string | "default";
  "symbolIcon.referenceForeground"?: string | "default";
  "symbolIcon.snippetForeground"?: string | "default";
  "symbolIcon.stringForeground"?: string | "default";
  "symbolIcon.structForeground"?: string | "default";
  "symbolIcon.textForeground"?: string | "default";
  "symbolIcon.typeParameterForeground"?: string | "default";
  "symbolIcon.unitForeground"?: string | "default";
  "symbolIcon.variableForeground"?: string | "default";
  "actionBar.toggledBackground"?: string | "default";
  "editorHoverWidget.highlightForeground"?: string | "default";
  "editor.lineHighlightBackground"?: string | "default";
  "editor.lineHighlightBorder"?: string | "default";
  "editor.rangeHighlightBackground"?: string | "default";
  "editor.rangeHighlightBorder"?: string | "default";
  "editor.symbolHighlightBackground"?: string | "default";
  "editor.symbolHighlightBorder"?: string | "default";
  "editorCursor.foreground"?: string | "default";
  "editorCursor.background"?: string | "default";
  "editorMultiCursor.primary.foreground"?: string | "default";
  "editorMultiCursor.primary.background"?: string | "default";
  "editorMultiCursor.secondary.foreground"?: string | "default";
  "editorMultiCursor.secondary.background"?: string | "default";
  "editorWhitespace.foreground"?: string | "default";
  "editorLineNumber.foreground"?: string | "default";
  "editorIndentGuide.background"?: string | "default";
  "editorIndentGuide.activeBackground"?: string | "default";
  "editorIndentGuide.background1"?: string | "default";
  "editorIndentGuide.background2"?: string | "default";
  "editorIndentGuide.background3"?: string | "default";
  "editorIndentGuide.background4"?: string | "default";
  "editorIndentGuide.background5"?: string | "default";
  "editorIndentGuide.background6"?: string | "default";
  "editorIndentGuide.activeBackground1"?: string | "default";
  "editorIndentGuide.activeBackground2"?: string | "default";
  "editorIndentGuide.activeBackground3"?: string | "default";
  "editorIndentGuide.activeBackground4"?: string | "default";
  "editorIndentGuide.activeBackground5"?: string | "default";
  "editorIndentGuide.activeBackground6"?: string | "default";
  "editorActiveLineNumber.foreground"?: string | "default";
  "editorLineNumber.activeForeground"?: string | "default";
  "editorLineNumber.dimmedForeground"?: string | "default";
  "editorRuler.foreground"?: string | "default";
  "editorCodeLens.foreground"?: string | "default";
  "editorBracketMatch.background"?: string | "default";
  "editorBracketMatch.border"?: string | "default";
  "editorOverviewRuler.border"?: string | "default";
  "editorOverviewRuler.background"?: string | "default";
  "editorGutter.background"?: string | "default";
  "editorUnnecessaryCode.border"?: string | "default";
  "editorUnnecessaryCode.opacity"?: string | "default";
  "editorGhostText.border"?: string | "default";
  "editorGhostText.foreground"?: string | "default";
  "editorGhostText.background"?: string | "default";
  "editorOverviewRuler.rangeHighlightForeground"?: string | "default";
  "editorOverviewRuler.errorForeground"?: string | "default";
  "editorOverviewRuler.warningForeground"?: string | "default";
  "editorOverviewRuler.infoForeground"?: string | "default";
  "editorBracketHighlight.foreground1"?: string | "default";
  "editorBracketHighlight.foreground2"?: string | "default";
  "editorBracketHighlight.foreground3"?: string | "default";
  "editorBracketHighlight.foreground4"?: string | "default";
  "editorBracketHighlight.foreground5"?: string | "default";
  "editorBracketHighlight.foreground6"?: string | "default";
  "editorBracketHighlight.unexpectedBracket.foreground"?: string | "default";
  "editorBracketPairGuide.background1"?: string | "default";
  "editorBracketPairGuide.background2"?: string | "default";
  "editorBracketPairGuide.background3"?: string | "default";
  "editorBracketPairGuide.background4"?: string | "default";
  "editorBracketPairGuide.background5"?: string | "default";
  "editorBracketPairGuide.background6"?: string | "default";
  "editorBracketPairGuide.activeBackground1"?: string | "default";
  "editorBracketPairGuide.activeBackground2"?: string | "default";
  "editorBracketPairGuide.activeBackground3"?: string | "default";
  "editorBracketPairGuide.activeBackground4"?: string | "default";
  "editorBracketPairGuide.activeBackground5"?: string | "default";
  "editorBracketPairGuide.activeBackground6"?: string | "default";
  "editorUnicodeHighlight.border"?: string | "default";
  "editorUnicodeHighlight.background"?: string | "default";
  "editor.placeholder.foreground"?: string | "default";
  "diffEditor.move.border"?: string | "default";
  "diffEditor.moveActive.border"?: string | "default";
  "diffEditor.unchangedRegionShadow"?: string | "default";
  "editorOverviewRuler.bracketMatchForeground"?: string | "default";
  "editor.foldBackground"?: string | "default";
  "editor.foldPlaceholderForeground"?: string | "default";
  "editorGutter.foldingControlForeground"?: string | "default";
  "editor.linkedEditingBackground"?: string | "default";
  "editor.wordHighlightBackground"?: string | "default";
  "editor.wordHighlightStrongBackground"?: string | "default";
  "editor.wordHighlightTextBackground"?: string | "default";
  "editor.wordHighlightBorder"?: string | "default";
  "editor.wordHighlightStrongBorder"?: string | "default";
  "editor.wordHighlightTextBorder"?: string | "default";
  "editorOverviewRuler.wordHighlightForeground"?: string | "default";
  "editorOverviewRuler.wordHighlightStrongForeground"?: string | "default";
  "editorOverviewRuler.wordHighlightTextForeground"?: string | "default";
  "peekViewTitle.background"?: string | "default";
  "peekViewTitleLabel.foreground"?: string | "default";
  "peekViewTitleDescription.foreground"?: string | "default";
  "peekView.border"?: string | "default";
  "peekViewResult.background"?: string | "default";
  "peekViewResult.lineForeground"?: string | "default";
  "peekViewResult.fileForeground"?: string | "default";
  "peekViewResult.selectionBackground"?: string | "default";
  "peekViewResult.selectionForeground"?: string | "default";
  "peekViewEditor.background"?: string | "default";
  "peekViewEditorGutter.background"?: string | "default";
  "peekViewEditorStickyScroll.background"?: string | "default";
  "peekViewResult.matchHighlightBackground"?: string | "default";
  "peekViewEditor.matchHighlightBackground"?: string | "default";
  "peekViewEditor.matchHighlightBorder"?: string | "default";
  "editorMarkerNavigationError.background"?: string | "default";
  "editorMarkerNavigationError.headerBackground"?: string | "default";
  "editorMarkerNavigationWarning.background"?: string | "default";
  "editorMarkerNavigationWarning.headerBackground"?: string | "default";
  "editorMarkerNavigationInfo.background"?: string | "default";
  "editorMarkerNavigationInfo.headerBackground"?: string | "default";
  "editorMarkerNavigation.background"?: string | "default";
  "editorSuggestWidget.background"?: string | "default";
  "editorSuggestWidget.border"?: string | "default";
  "editorSuggestWidget.foreground"?: string | "default";
  "editorSuggestWidget.selectedForeground"?: string | "default";
  "editorSuggestWidget.selectedIconForeground"?: string | "default";
  "editorSuggestWidget.selectedBackground"?: string | "default";
  "editorSuggestWidget.highlightForeground"?: string | "default";
  "editorSuggestWidget.focusHighlightForeground"?: string | "default";
  "editorSuggestWidgetStatus.foreground"?: string | "default";
  "editorWatermark.foreground"?: string | "default";
  "tab.activeBackground"?: string | "default";
  "tab.unfocusedActiveBackground"?: string | "default";
  "tab.inactiveBackground"?: string | "default";
  "tab.unfocusedInactiveBackground"?: string | "default";
  "tab.activeForeground"?: string | "default";
  "tab.inactiveForeground"?: string | "default";
  "tab.unfocusedActiveForeground"?: string | "default";
  "tab.unfocusedInactiveForeground"?: string | "default";
  "tab.hoverBackground"?: string | "default";
  "tab.unfocusedHoverBackground"?: string | "default";
  "tab.hoverForeground"?: string | "default";
  "tab.unfocusedHoverForeground"?: string | "default";
  "tab.border"?: string | "default";
  "tab.lastPinnedBorder"?: string | "default";
  "tab.activeBorder"?: string | "default";
  "tab.unfocusedActiveBorder"?: string | "default";
  "tab.activeBorderTop"?: string | "default";
  "tab.unfocusedActiveBorderTop"?: string | "default";
  "tab.selectedBorderTop"?: string | "default";
  "tab.selectedBackground"?: string | "default";
  "tab.selectedForeground"?: string | "default";
  "tab.hoverBorder"?: string | "default";
  "tab.unfocusedHoverBorder"?: string | "default";
  "tab.dragAndDropBorder"?: string | "default";
  "tab.activeModifiedBorder"?: string | "default";
  "tab.inactiveModifiedBorder"?: string | "default";
  "tab.unfocusedActiveModifiedBorder"?: string | "default";
  "tab.unfocusedInactiveModifiedBorder"?: string | "default";
  "editorPane.background"?: string | "default";
  "editorGroup.emptyBackground"?: string | "default";
  "editorGroup.focusedEmptyBorder"?: string | "default";
  "editorGroupHeader.tabsBackground"?: string | "default";
  "editorGroupHeader.tabsBorder"?: string | "default";
  "editorGroupHeader.noTabsBackground"?: string | "default";
  "editorGroupHeader.border"?: string | "default";
  "editorGroup.border"?: string | "default";
  "editorGroup.dropBackground"?: string | "default";
  "editorGroup.dropIntoPromptForeground"?: string | "default";
  "editorGroup.dropIntoPromptBackground"?: string | "default";
  "editorGroup.dropIntoPromptBorder"?: string | "default";
  "sideBySideEditor.horizontalBorder"?: string | "default";
  "sideBySideEditor.verticalBorder"?: string | "default";
  "panel.background"?: string | "default";
  "panel.border"?: string | "default";
  "panelTitle.activeForeground"?: string | "default";
  "panelTitle.inactiveForeground"?: string | "default";
  "panelTitle.activeBorder"?: string | "default";
  "panelInput.border"?: string | "default";
  "panel.dropBorder"?: string | "default";
  "panelSection.dropBackground"?: string | "default";
  "panelSectionHeader.background"?: string | "default";
  "panelSectionHeader.foreground"?: string | "default";
  "panelSectionHeader.border"?: string | "default";
  "panelSection.border"?: string | "default";
  "panelStickyScroll.background"?: string | "default";
  "panelStickyScroll.border"?: string | "default";
  "panelStickyScroll.shadow"?: string | "default";
  "outputView.background"?: string | "default";
  "outputViewStickyScroll.background"?: string | "default";
  "banner.background"?: string | "default";
  "banner.foreground"?: string | "default";
  "banner.iconForeground"?: string | "default";
  "statusBar.foreground"?: string | "default";
  "statusBar.noFolderForeground"?: string | "default";
  "statusBar.background"?: string | "default";
  "statusBar.noFolderBackground"?: string | "default";
  "statusBar.border"?: string | "default";
  "statusBar.focusBorder"?: string | "default";
  "statusBar.noFolderBorder"?: string | "default";
  "statusBarItem.activeBackground"?: string | "default";
  "statusBarItem.focusBorder"?: string | "default";
  "statusBarItem.hoverBackground"?: string | "default";
  "statusBarItem.hoverForeground"?: string | "default";
  "statusBarItem.compactHoverBackground"?: string | "default";
  "statusBarItem.prominentForeground"?: string | "default";
  "statusBarItem.prominentBackground"?: string | "default";
  "statusBarItem.prominentHoverForeground"?: string | "default";
  "statusBarItem.prominentHoverBackground"?: string | "default";
  "statusBarItem.errorBackground"?: string | "default";
  "statusBarItem.errorForeground"?: string | "default";
  "statusBarItem.errorHoverForeground"?: string | "default";
  "statusBarItem.errorHoverBackground"?: string | "default";
  "statusBarItem.warningBackground"?: string | "default";
  "statusBarItem.warningForeground"?: string | "default";
  "statusBarItem.warningHoverForeground"?: string | "default";
  "statusBarItem.warningHoverBackground"?: string | "default";
  "activityBar.background"?: string | "default";
  "activityBar.foreground"?: string | "default";
  "activityBar.inactiveForeground"?: string | "default";
  "activityBar.border"?: string | "default";
  "activityBar.activeBorder"?: string | "default";
  "activityBar.activeFocusBorder"?: string | "default";
  "activityBar.activeBackground"?: string | "default";
  "activityBar.dropBorder"?: string | "default";
  "activityBarBadge.background"?: string | "default";
  "activityBarBadge.foreground"?: string | "default";
  "activityBarTop.foreground"?: string | "default";
  "activityBarTop.activeBorder"?: string | "default";
  "activityBarTop.activeBackground"?: string | "default";
  "activityBarTop.inactiveForeground"?: string | "default";
  "activityBarTop.dropBorder"?: string | "default";
  "activityBarTop.background"?: string | "default";
  "profileBadge.background"?: string | "default";
  "profileBadge.foreground"?: string | "default";
  "statusBarItem.remoteBackground"?: string | "default";
  "statusBarItem.remoteForeground"?: string | "default";
  "statusBarItem.remoteHoverForeground"?: string | "default";
  "statusBarItem.remoteHoverBackground"?: string | "default";
  "statusBarItem.offlineBackground"?: string | "default";
  "statusBarItem.offlineForeground"?: string | "default";
  "statusBarItem.offlineHoverForeground"?: string | "default";
  "statusBarItem.offlineHoverBackground"?: string | "default";
  "extensionBadge.remoteBackground"?: string | "default";
  "extensionBadge.remoteForeground"?: string | "default";
  "sideBar.background"?: string | "default";
  "sideBar.foreground"?: string | "default";
  "sideBar.border"?: string | "default";
  "sideBarTitle.background"?: string | "default";
  "sideBarTitle.foreground"?: string | "default";
  "sideBar.dropBackground"?: string | "default";
  "sideBarSectionHeader.background"?: string | "default";
  "sideBarSectionHeader.foreground"?: string | "default";
  "sideBarSectionHeader.border"?: string | "default";
  "sideBarActivityBarTop.border"?: string | "default";
  "sideBarStickyScroll.background"?: string | "default";
  "sideBarStickyScroll.border"?: string | "default";
  "sideBarStickyScroll.shadow"?: string | "default";
  "titleBar.activeForeground"?: string | "default";
  "titleBar.inactiveForeground"?: string | "default";
  "titleBar.activeBackground"?: string | "default";
  "titleBar.inactiveBackground"?: string | "default";
  "titleBar.border"?: string | "default";
  "menubar.selectionForeground"?: string | "default";
  "menubar.selectionBackground"?: string | "default";
  "menubar.selectionBorder"?: string | "default";
  "commandCenter.foreground"?: string | "default";
  "commandCenter.activeForeground"?: string | "default";
  "commandCenter.inactiveForeground"?: string | "default";
  "commandCenter.background"?: string | "default";
  "commandCenter.activeBackground"?: string | "default";
  "commandCenter.border"?: string | "default";
  "commandCenter.activeBorder"?: string | "default";
  "commandCenter.inactiveBorder"?: string | "default";
  "notificationCenter.border"?: string | "default";
  "notificationToast.border"?: string | "default";
  "notifications.foreground"?: string | "default";
  "notifications.background"?: string | "default";
  "notificationLink.foreground"?: string | "default";
  "notificationCenterHeader.foreground"?: string | "default";
  "notificationCenterHeader.background"?: string | "default";
  "notifications.border"?: string | "default";
  "notificationsErrorIcon.foreground"?: string | "default";
  "notificationsWarningIcon.foreground"?: string | "default";
  "notificationsInfoIcon.foreground"?: string | "default";
  "window.activeBorder"?: string | "default";
  "window.inactiveBorder"?: string | "default";
  "chat.requestBorder"?: string | "default";
  "chat.requestBackground"?: string | "default";
  "chat.slashCommandBackground"?: string | "default";
  "chat.slashCommandForeground"?: string | "default";
  "chat.avatarBackground"?: string | "default";
  "chat.avatarForeground"?: string | "default";
  "simpleFindWidget.sashBorder"?: string | "default";
  "commentsView.resolvedIcon"?: string | "default";
  "commentsView.unresolvedIcon"?: string | "default";
  "editorCommentsWidget.replyInputBackground"?: string | "default";
  "editorCommentsWidget.resolvedBorder"?: string | "default";
  "editorCommentsWidget.unresolvedBorder"?: string | "default";
  "editorCommentsWidget.rangeBackground"?: string | "default";
  "editorCommentsWidget.rangeActiveBackground"?: string | "default";
  "editorGutter.commentRangeForeground"?: string | "default";
  "editorOverviewRuler.commentForeground"?: string | "default";
  "editorOverviewRuler.commentUnresolvedForeground"?: string | "default";
  "editorGutter.commentGlyphForeground"?: string | "default";
  "editorGutter.commentUnresolvedGlyphForeground"?: string | "default";
  "debugToolBar.background"?: string | "default";
  "debugToolBar.border"?: string | "default";
  "debugIcon.startForeground"?: string | "default";
  "editor.stackFrameHighlightBackground"?: string | "default";
  "editor.focusedStackFrameHighlightBackground"?: string | "default";
  "inlineChat.foreground"?: string | "default";
  "inlineChat.background"?: string | "default";
  "inlineChat.border"?: string | "default";
  "inlineChat.shadow"?: string | "default";
  "inlineChatInput.border"?: string | "default";
  "inlineChatInput.focusBorder"?: string | "default";
  "inlineChatInput.placeholderForeground"?: string | "default";
  "inlineChatInput.background"?: string | "default";
  "inlineChatDiff.inserted"?: string | "default";
  "editorOverviewRuler.inlineChatInserted"?: string | "default";
  "inlineChatDiff.removed"?: string | "default";
  "editorOverviewRuler.inlineChatRemoved"?: string | "default";
  "mergeEditor.change.background"?: string | "default";
  "mergeEditor.change.word.background"?: string | "default";
  "mergeEditor.changeBase.background"?: string | "default";
  "mergeEditor.changeBase.word.background"?: string | "default";
  "mergeEditor.conflict.unhandledUnfocused.border"?: string | "default";
  "mergeEditor.conflict.unhandledFocused.border"?: string | "default";
  "mergeEditor.conflict.handledUnfocused.border"?: string | "default";
  "mergeEditor.conflict.handledFocused.border"?: string | "default";
  "mergeEditor.conflict.handled.minimapOverViewRuler"?: string | "default";
  "mergeEditor.conflict.unhandled.minimapOverViewRuler"?: string | "default";
  "mergeEditor.conflictingLines.background"?: string | "default";
  "mergeEditor.conflict.input1.background"?: string | "default";
  "mergeEditor.conflict.input2.background"?: string | "default";
  "settings.headerForeground"?: string | "default";
  "settings.settingsHeaderHoverForeground"?: string | "default";
  "settings.modifiedItemIndicator"?: string | "default";
  "settings.headerBorder"?: string | "default";
  "settings.sashBorder"?: string | "default";
  "settings.dropdownBackground"?: string | "default";
  "settings.dropdownForeground"?: string | "default";
  "settings.dropdownBorder"?: string | "default";
  "settings.dropdownListBorder"?: string | "default";
  "settings.checkboxBackground"?: string | "default";
  "settings.checkboxForeground"?: string | "default";
  "settings.checkboxBorder"?: string | "default";
  "settings.textInputBackground"?: string | "default";
  "settings.textInputForeground"?: string | "default";
  "settings.textInputBorder"?: string | "default";
  "settings.numberInputBackground"?: string | "default";
  "settings.numberInputForeground"?: string | "default";
  "settings.numberInputBorder"?: string | "default";
  "settings.focusedRowBackground"?: string | "default";
  "settings.rowHoverBackground"?: string | "default";
  "settings.focusedRowBorder"?: string | "default";
  "terminal.background"?: string | "default";
  "terminal.foreground"?: string | "default";
  "terminalCursor.foreground"?: string | "default";
  "terminalCursor.background"?: string | "default";
  "terminal.selectionBackground"?: string | "default";
  "terminal.inactiveSelectionBackground"?: string | "default";
  "terminal.selectionForeground"?: string | "default";
  "terminalCommandDecoration.defaultBackground"?: string | "default";
  "terminalCommandDecoration.successBackground"?: string | "default";
  "terminalCommandDecoration.errorBackground"?: string | "default";
  "terminalOverviewRuler.cursorForeground"?: string | "default";
  "terminal.border"?: string | "default";
  "terminal.findMatchBackground"?: string | "default";
  "terminal.hoverHighlightBackground"?: string | "default";
  "terminal.findMatchBorder"?: string | "default";
  "terminal.findMatchHighlightBackground"?: string | "default";
  "terminal.findMatchHighlightBorder"?: string | "default";
  "terminalOverviewRuler.findMatchForeground"?: string | "default";
  "terminal.dropBackground"?: string | "default";
  "terminal.tab.activeBorder"?: string | "default";
  "terminal.initialHintForeground"?: string | "default";
  "terminalStickyScroll.background"?: string | "default";
  "terminalStickyScrollHover.background"?: string | "default";
  "terminalStickyScroll.border"?: string | "default";
  "testing.iconFailed"?: string | "default";
  "testing.iconErrored"?: string | "default";
  "testing.iconPassed"?: string | "default";
  "testing.runAction"?: string | "default";
  "testing.iconQueued"?: string | "default";
  "testing.iconUnset"?: string | "default";
  "testing.iconSkipped"?: string | "default";
  "testing.peekBorder"?: string | "default";
  "testing.messagePeekBorder"?: string | "default";
  "testing.peekHeaderBackground"?: string | "default";
  "testing.messagePeekHeaderBackground"?: string | "default";
  "testing.coveredBackground"?: string | "default";
  "testing.coveredBorder"?: string | "default";
  "testing.coveredGutterBackground"?: string | "default";
  "testing.uncoveredBranchBackground"?: string | "default";
  "testing.uncoveredBackground"?: string | "default";
  "testing.uncoveredBorder"?: string | "default";
  "testing.uncoveredGutterBackground"?: string | "default";
  "testing.coverCountBadgeBackground"?: string | "default";
  "testing.coverCountBadgeForeground"?: string | "default";
  "testing.message.error.decorationForeground"?: string | "default";
  "testing.message.error.lineBackground"?: string | "default";
  "testing.message.info.decorationForeground"?: string | "default";
  "testing.message.info.lineBackground"?: string | "default";
  "testing.iconErrored.retired"?: string | "default";
  "testing.iconFailed.retired"?: string | "default";
  "testing.iconPassed.retired"?: string | "default";
  "testing.iconQueued.retired"?: string | "default";
  "testing.iconUnset.retired"?: string | "default";
  "testing.iconSkipped.retired"?: string | "default";
  "welcomePage.background"?: string | "default";
  "welcomePage.tileBackground"?: string | "default";
  "welcomePage.tileHoverBackground"?: string | "default";
  "welcomePage.tileBorder"?: string | "default";
  "welcomePage.progress.background"?: string | "default";
  "welcomePage.progress.foreground"?: string | "default";
  "walkthrough.stepTitle.foreground"?: string | "default";
  "walkThrough.embeddedEditorBackground"?: string | "default";
  "debugExceptionWidget.border"?: string | "default";
  "debugExceptionWidget.background"?: string | "default";
  "statusBar.debuggingBackground"?: string | "default";
  "statusBar.debuggingForeground"?: string | "default";
  "statusBar.debuggingBorder"?: string | "default";
  "commandCenter.debuggingBackground"?: string | "default";
  "editorGutter.modifiedBackground"?: string | "default";
  "editorGutter.addedBackground"?: string | "default";
  "editorGutter.deletedBackground"?: string | "default";
  "minimapGutter.modifiedBackground"?: string | "default";
  "minimapGutter.addedBackground"?: string | "default";
  "minimapGutter.deletedBackground"?: string | "default";
  "editorOverviewRuler.modifiedForeground"?: string | "default";
  "editorOverviewRuler.addedForeground"?: string | "default";
  "editorOverviewRuler.deletedForeground"?: string | "default";
  "keybindingTable.headerBackground"?: string | "default";
  "keybindingTable.rowsBackground"?: string | "default";
  "debugIcon.breakpointForeground"?: string | "default";
  "debugIcon.breakpointDisabledForeground"?: string | "default";
  "debugIcon.breakpointUnverifiedForeground"?: string | "default";
  "debugIcon.breakpointCurrentStackframeForeground"?: string | "default";
  "debugIcon.breakpointStackframeForeground"?: string | "default";
  "editor.inlineValuesForeground"?: string | "default";
  "editor.inlineValuesBackground"?: string | "default";
  "ports.iconRunningProcessForeground"?: string | "default";
  "profiles.sashBorder"?: string | "default";
  "debugTokenExpression.name"?: string | "default";
  "debugTokenExpression.type"?: string | "default";
  "debugTokenExpression.value"?: string | "default";
  "debugTokenExpression.string"?: string | "default";
  "debugTokenExpression.boolean"?: string | "default";
  "debugTokenExpression.number"?: string | "default";
  "debugTokenExpression.error"?: string | "default";
  "debugView.exceptionLabelForeground"?: string | "default";
  "debugView.exceptionLabelBackground"?: string | "default";
  "debugView.stateLabelForeground"?: string | "default";
  "debugView.stateLabelBackground"?: string | "default";
  "debugView.valueChangedHighlight"?: string | "default";
  "debugConsole.infoForeground"?: string | "default";
  "debugConsole.warningForeground"?: string | "default";
  "debugConsole.errorForeground"?: string | "default";
  "debugConsole.sourceForeground"?: string | "default";
  "debugConsoleInputIcon.foreground"?: string | "default";
  "debugIcon.pauseForeground"?: string | "default";
  "debugIcon.stopForeground"?: string | "default";
  "debugIcon.disconnectForeground"?: string | "default";
  "debugIcon.restartForeground"?: string | "default";
  "debugIcon.stepOverForeground"?: string | "default";
  "debugIcon.stepIntoForeground"?: string | "default";
  "debugIcon.stepOutForeground"?: string | "default";
  "debugIcon.continueForeground"?: string | "default";
  "debugIcon.stepBackForeground"?: string | "default";
  "scm.historyItemAdditionsForeground"?: string | "default";
  "scm.historyItemDeletionsForeground"?: string | "default";
  "scm.historyItemStatisticsBorder"?: string | "default";
  "scm.historyItemSelectedStatisticsBorder"?: string | "default";
  "extensionButton.background"?: string | "default";
  "extensionButton.foreground"?: string | "default";
  "extensionButton.hoverBackground"?: string | "default";
  "extensionButton.separator"?: string | "default";
  "extensionButton.prominentBackground"?: string | "default";
  "extensionButton.prominentForeground"?: string | "default";
  "extensionButton.prominentHoverBackground"?: string | "default";
  "extensionIcon.starForeground"?: string | "default";
  "extensionIcon.verifiedForeground"?: string | "default";
  "extensionIcon.preReleaseForeground"?: string | "default";
  "extensionIcon.sponsorForeground"?: string | "default";
  "notebook.cellBorderColor"?: string | "default";
  "notebook.focusedEditorBorder"?: string | "default";
  "notebookStatusSuccessIcon.foreground"?: string | "default";
  "notebookEditorOverviewRuler.runningCellForeground"?: string | "default";
  "notebookStatusErrorIcon.foreground"?: string | "default";
  "notebookStatusRunningIcon.foreground"?: string | "default";
  "notebook.outputContainerBorderColor"?: string | "default";
  "notebook.outputContainerBackgroundColor"?: string | "default";
  "notebook.cellToolbarSeparator"?: string | "default";
  "notebook.focusedCellBackground"?: string | "default";
  "notebook.selectedCellBackground"?: string | "default";
  "notebook.cellHoverBackground"?: string | "default";
  "notebook.selectedCellBorder"?: string | "default";
  "notebook.inactiveSelectedCellBorder"?: string | "default";
  "notebook.focusedCellBorder"?: string | "default";
  "notebook.inactiveFocusedCellBorder"?: string | "default";
  "notebook.cellStatusBarItemHoverBackground"?: string | "default";
  "notebook.cellInsertionIndicator"?: string | "default";
  "notebookScrollbarSlider.background"?: string | "default";
  "notebookScrollbarSlider.hoverBackground"?: string | "default";
  "notebookScrollbarSlider.activeBackground"?: string | "default";
  "notebook.symbolHighlightBackground"?: string | "default";
  "notebook.cellEditorBackground"?: string | "default";
  "notebook.editorBackground"?: string | "default";
  "interactive.activeCodeBorder"?: string | "default";
  "interactive.inactiveCodeBorder"?: string | "default";
  "searchEditor.textInputBorder"?: string | "default";
  "terminal.ansiBlack"?: string | "default";
  "terminal.ansiRed"?: string | "default";
  "terminal.ansiGreen"?: string | "default";
  "terminal.ansiYellow"?: string | "default";
  "terminal.ansiBlue"?: string | "default";
  "terminal.ansiMagenta"?: string | "default";
  "terminal.ansiCyan"?: string | "default";
  "terminal.ansiWhite"?: string | "default";
  "terminal.ansiBrightBlack"?: string | "default";
  "terminal.ansiBrightRed"?: string | "default";
  "terminal.ansiBrightGreen"?: string | "default";
  "terminal.ansiBrightYellow"?: string | "default";
  "terminal.ansiBrightBlue"?: string | "default";
  "terminal.ansiBrightMagenta"?: string | "default";
  "terminal.ansiBrightCyan"?: string | "default";
  "terminal.ansiBrightWhite"?: string | "default";
  "gitDecoration.addedResourceForeground"?: string | "default";
  "gitDecoration.modifiedResourceForeground"?: string | "default";
  "gitDecoration.deletedResourceForeground"?: string | "default";
  "gitDecoration.renamedResourceForeground"?: string | "default";
  "gitDecoration.untrackedResourceForeground"?: string | "default";
  "gitDecoration.ignoredResourceForeground"?: string | "default";
  "gitDecoration.stageModifiedResourceForeground"?: string | "default";
  "gitDecoration.stageDeletedResourceForeground"?: string | "default";
  "gitDecoration.conflictingResourceForeground"?: string | "default";
  "gitDecoration.submoduleResourceForeground"?: string | "default";
  "bookmarks.lineBackground"?: string | "default";
  "bookmarks.lineBorder"?: string | "default";
  "bookmarks.overviewRuler"?: string | "default";
  "remoteHub.decorations.addedForegroundColor"?: string | "default";
  "remoteHub.decorations.modifiedForegroundColor"?: string | "default";
  "remoteHub.decorations.deletedForegroundColor"?: string | "default";
  "remoteHub.decorations.submoduleForegroundColor"?: string | "default";
  "remoteHub.decorations.conflictForegroundColor"?: string | "default";
  "remoteHub.decorations.incomingAddedForegroundColor"?: string | "default";
  "remoteHub.decorations.incomingModifiedForegroundColor"?: string | "default";
  "remoteHub.decorations.incomingDeletedForegroundColor"?: string | "default";
  "remoteHub.decorations.incomingRenamedForegroundColor"?: string | "default";
  "remoteHub.decorations.possibleConflictForegroundColor"?: string | "default";
  "remoteHub.decorations.ignoredResourceForeground"?: string | "default";
  "remoteHub.decorations.workspaceRepositoriesView.hasUncommittedChangesForegroundColor"?: string | "default";
  "rust_analyzer.syntaxTreeBorder"?: string | "default";
  "errorLens.errorBackground"?: string | "default";
  "errorLens.errorMessageBackground"?: string | "default";
  "errorLens.errorRangeBackground"?: string | "default";
  "errorLens.errorBackgroundLight"?: string | "default";
  "errorLens.errorForeground"?: string | "default";
  "errorLens.errorForegroundLight"?: string | "default";
  "errorLens.warningBackground"?: string | "default";
  "errorLens.warningMessageBackground"?: string | "default";
  "errorLens.warningRangeBackground"?: string | "default";
  "errorLens.warningBackgroundLight"?: string | "default";
  "errorLens.warningForeground"?: string | "default";
  "errorLens.warningForegroundLight"?: string | "default";
  "errorLens.infoBackground"?: string | "default";
  "errorLens.infoMessageBackground"?: string | "default";
  "errorLens.infoRangeBackground"?: string | "default";
  "errorLens.infoBackgroundLight"?: string | "default";
  "errorLens.infoForeground"?: string | "default";
  "errorLens.infoForegroundLight"?: string | "default";
  "errorLens.hintBackground"?: string | "default";
  "errorLens.hintMessageBackground"?: string | "default";
  "errorLens.hintRangeBackground"?: string | "default";
  "errorLens.hintBackgroundLight"?: string | "default";
  "errorLens.hintForeground"?: string | "default";
  "errorLens.hintForegroundLight"?: string | "default";
  "errorLens.statusBarIconErrorForeground"?: string | "default";
  "errorLens.statusBarIconWarningForeground"?: string | "default";
  "errorLens.statusBarErrorForeground"?: string | "default";
  "errorLens.statusBarWarningForeground"?: string | "default";
  "errorLens.statusBarInfoForeground"?: string | "default";
  "errorLens.statusBarHintForeground"?: string | "default";
  "gitblame.inlineMessage"?: string | "default";
}
/**
 * Colors and styles for the token.
 */
export interface Settings {
  /**
   * Foreground color for the token.
   */
  foreground?: string;
  background?: string;
  /**
   * Font style of the rule: 'italic', 'bold', 'underline', 'strikethrough' or a combination. The empty string unsets inherited settings.
   */
  fontStyle?: string;
}
/**
 * Colors for semantic tokens
 */
export interface TokenStyling {
  /**
   * Style for comments.
   */
  comment?: string | Style;
  /**
   * Style for strings.
   */
  string?: string | Style;
  /**
   * Style for keywords.
   */
  keyword?: string | Style;
  /**
   * Style for numbers.
   */
  number?: string | Style;
  /**
   * Style for expressions.
   */
  regexp?: string | Style;
  /**
   * Style for operators
   */
  operator?: string | Style;
  /**
   * Style for namespaces.
   */
  namespace?: string | Style;
  /**
   * Style for types.
   */
  type?: string | Style;
  /**
   * Style for structs.
   */
  struct?: string | Style;
  /**
   * Style for classes.
   */
  class?: string | Style;
  /**
   * Style for interfaces.
   */
  interface?: string | Style;
  /**
   * Style for enums.
   */
  enum?: string | Style;
  /**
   * Style for type parameters.
   */
  typeParameter?: string | Style;
  /**
   * Style for functions
   */
  function?: string | Style;
  /**
   * Style for member functions
   */
  member?: string | Style;
  /**
   * Style for method (member functions)
   */
  method?: string | Style;
  /**
   * Style for macros.
   */
  macro?: string | Style;
  /**
   * Style for variables.
   */
  variable?: string | Style;
  /**
   * Style for parameters.
   */
  parameter?: string | Style;
  /**
   * Style for properties.
   */
  property?: string | Style;
  /**
   * Style for enum members.
   */
  enumMember?: string | Style;
  /**
   * Style for events.
   */
  event?: string | Style;
  /**
   * Style for decorators & annotations.
   */
  decorator?: string | Style;
  /**
   * Style for labels
   */
  label?: string | Style;
  /**
   * Style for all symbol declarations.
   */
  "*.declaration"?: string | Style;
  /**
   * Style to use for references in documentation.
   */
  "*.documentation"?: string | Style;
  /**
   * Style to use for symbols that are static.
   */
  "*.static"?: string | Style;
  /**
   * Style to use for symbols that are abstract.
   */
  "*.abstract"?: string | Style;
  /**
   * Style to use for symbols that are deprecated.
   */
  "*.deprecated"?: string | Style;
  /**
   * Style to use for write accesses.
   */
  "*.modification"?: string | Style;
  /**
   * Style for async functions and the `async` and `await` keywords
   */
  "*.async"?: string | Style;
  /**
   * Style to use for symbols that are read-only.
   */
  "*.readonly"?: string | Style;
  /**
   * Style for < or >
   */
  angle?: string | Style;
  /**
   * Style for arithmetic operators
   */
  arithmetic?: string | Style;
  /**
   * Style for attributes
   */
  attribute?: string | Style;
  /**
   * Style for attribute invocation brackets, that is the `#[` and `]` tokens
   */
  attributeBracket?: string | Style;
  /**
   * Style for bitwise operators
   */
  bitwise?: string | Style;
  /**
   * Style for boolean literals
   */
  boolean?: string | Style;
  /**
   * Style for { or }
   */
  brace?: string | Style;
  /**
   * Style for [ or ]
   */
  bracket?: string | Style;
  /**
   * Style for builtin attributes
   */
  builtinAttribute?: string | Style;
  /**
   * Style for builtin types
   */
  builtinType?: string | Style;
  /**
   * Style for character literals
   */
  character?: string | Style;
  /**
   * Style for :
   */
  colon?: string | Style;
  /**
   * Style for ,
   */
  comma?: string | Style;
  /**
   * Style for comparison operators
   */
  comparison?: string | Style;
  /**
   * Style for const generics
   */
  constParameter?: string | Style;
  /**
   * Style for consts
   */
  const?: string | Style;
  /**
   * Style for derives
   */
  derive?: string | Style;
  /**
   * Style for derive helpers
   */
  deriveHelper?: string | Style;
  /**
   * Style for .
   */
  dot?: string | Style;
  /**
   * Style for char or byte escapes in strings
   */
  escapeSequence?: string | Style;
  /**
   * Style for {} placeholders in format strings
   */
  formatSpecifier?: string | Style;
  /**
   * Style for invalid char or byte escapes in strings
   */
  invalidEscapeSequence?: string | Style;
  /**
   * Style for lifetimes
   */
  lifetime?: string | Style;
  /**
   * Style for logic operators
   */
  logical?: string | Style;
  /**
   * Style for the ! token of macro calls
   */
  macroBang?: string | Style;
  /**
   * Style for ( or )
   */
  parenthesis?: string | Style;
  /**
   * Style for proc macro code
   */
  procMacro?: string | Style;
  /**
   * Style for generic punctuation
   */
  punctuation?: string | Style;
  /**
   * Style for the self keyword
   */
  selfKeyword?: string | Style;
  /**
   * Style for the self type keyword
   */
  selfTypeKeyword?: string | Style;
  /**
   * Style for ;
   */
  semicolon?: string | Style;
  /**
   * Style for statics
   */
  static?: string | Style;
  /**
   * Style for tool module attributes
   */
  toolModule?: string | Style;
  /**
   * Style for type aliases
   */
  typeAlias?: string | Style;
  /**
   * Style for C-style untagged unions
   */
  union?: string | Style;
  /**
   * Style for names which can not be resolved due to compilation errors
   */
  unresolvedReference?: string | Style;
  /**
   * Keys of regular arrays.
   */
  tomlArrayKey?: string | Style;
  /**
   * Keys of inline tables.
   */
  tomlTableKey?: string | Style;
  /**
   * Style for elements within attributes
   */
  "*.attribute"?: string | Style;
  /**
   * Style for locals whose types implements one of the `Fn*` traits
   */
  "*.callable"?: string | Style;
  /**
   * Style for compile-time constants
   */
  "*.constant"?: string | Style;
  /**
   * Style for locals that are being consumed when use in a function call
   */
  "*.consuming"?: string | Style;
  /**
   * Style for control-flow related tokens, this includes the `?` operator
   */
  "*.controlFlow"?: string | Style;
  /**
   * Style for names resolving to a crate root
   */
  "*.crateRoot"?: string | Style;
  /**
   * Style for doc-string injected highlighting like rust source blocks in documentation
   */
  "*.injected"?: string | Style;
  /**
   * Style for intra doc links in doc-strings
   */
  "*.intraDocLink"?: string | Style;
  /**
   * Style for items that are defined outside of the current crate
   */
  "*.library"?: string | Style;
  /**
   * Style for tokens inside of macro calls
   */
  "*.macro"?: string | Style;
  /**
   * Style for mutable locals and statics as well as functions taking `&mut self`
   */
  "*.mutable"?: string | Style;
  /**
   * Style for tokens inside of proc-macro calls
   */
  "*.procMacro"?: string | Style;
  /**
   * Style for items that are from the current crate and are `pub`
   */
  "*.public"?: string | Style;
  /**
   * Style for locals behind a reference and functions taking `self` by reference
   */
  "*.reference"?: string | Style;
  /**
   * Style for associated trait items
   */
  "*.trait"?: string | Style;
  /**
   * Style for unsafe operations, like unsafe function calls, as well as the `unsafe` token
   */
  "*.unsafe"?: string | Style;
  /**
   * This interface was referenced by `TokenStyling`'s JSON-Schema definition
   * via the `patternProperty` "^(\w+[-_\w+]*|\*)(\.\w+[-_\w+]*)*(:\w+[-_\w+]*)?$".
   */
  [k: string]: string | Style;
}
/**
 * Colors and styles for the token.
 */
export interface Style {
  /**
   * Foreground color for the token.
   */
  foreground?: string;
  background?: string;
  /**
   * Sets the all font styles of the rule: 'italic', 'bold', 'underline' or 'strikethrough' or a combination. All styles that are not listed are unset. The empty string unsets all styles.
   */
  fontStyle?: string;
  /**
   * Sets or unsets the font style to bold. Note, the presence of 'fontStyle' overrides this setting.
   */
  bold?: boolean;
  /**
   * Sets or unsets the font style to italic. Note, the presence of 'fontStyle' overrides this setting.
   */
  italic?: boolean;
  /**
   * Sets or unsets the font style to underline. Note, the presence of 'fontStyle' overrides this setting.
   */
  underline?: boolean;
  /**
   * Sets or unsets the font style to strikethrough. Note, the presence of 'fontStyle' overrides this setting.
   */
  strikethrough?: boolean;
  [k: string]: unknown;
}
